[build]
  command = "GOBIN=$(pwd)/functions go install ./..."
  functions = "functions"

[build.environment]
  GO_IMPORT_PATH = "github.com/amalshaji/go-netlify"
  GO111MODULE = "on"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/gateway/:splat"
  status = 200